---
title: "Jae Yeon Kim's resume"
author: Jae Yeon Kim
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---


Aside
================================================================================

Last updated on `r Sys.Date()`.

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> jaeyeonkim@berkeley.edu

- <i class="fa fa-link"></i> [jaeyk.github.io](https://jaeyk.github.io/)

- <i class="fa fa-github"></i> [github.com/jaeyk](https://github.com/jaeyk/)

- <i class="fa fa-linkedin"></i> [linkedin.com/jae-yeon-kim](https://www.linkedin.com/in/jae-yeon-kim/)

- <i class="fa fa-phone"></i> +1 510-646-5183

- For more information, please contact me via email.


Coursework
--------------------------------------------------------------------------------

Statistical and Causal Inference, Experimental Design, Survey Methods, Game Theory, Computational Social Science

Passed [Political Behavior](https://polisci.berkeley.edu/research-and-teaching/subfields/political-behavior) (social and cognitive psychology, survey and experimental
design) field exam with distinction 

Skills {#skills}
--------------------------------------------------------------------------------

- <i class="fa fa-calculator"></i> **Quantitative**: Statistical and causal inference, Experimental and survey design

- <i class="fa fa-laptop"></i> **Computational**: Natural language processing, Machine learning, R (tidyr, dplyr, ggplot2, statistical packages), Python (pandas, scikit-learn), Git, SQL (PostgreSQL), Linux Command Line

Main
================================================================================

Jae Yeon Kim {#title}
--------------------------------------------------------------------------------

### Overview 

- Computational social scientist using data science to advance social science research on diversity and inclusion. 
- Extensive experience working with survey, experimental, administrative, and text data using statistical and machine learning methods. 

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### University of California, Berkeley

PhD Candidate in Political Science

Berkeley, California, USA

2016 - Present

### [Summer Institute in Computational Social Science](https://compsocialscience.github.io/summer-institute/2019/princeton/people)

Participant (10% acceptance rate)

Princeton University, Princeton, USA

Summer 2019

### University of California, Berkeley

MA in Political Science

Berkeley, California, USA

2014 - 2016

### Korea University 

BA in Political Science, Linguistics, and English

Seoul, South Korea 

2012

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data Science Fellow, Consultant, and Instructor

[Data-intensive Social Sciences Lab](https://dlab.berkeley.edu/)

UC Berkeley

May 2019 - Present

- Consulted Berkeley faculty, students, and staff on applied statistics, machine learning, data wrangling, and visualization
- Founded the working group on the bias in machine learning
- Developed [SQL for R Users](https://github.com/dlab-berkeley/sql-for-r-users) and [Advanced Data Wrangling Techniques in R](https://github.com/dlab-berkeley/advanced-data-wrangling-in-R) workshops

### Data Science Education Program Fellow

[Data Science Education Program](https://ais.berkeley.edu/departments/data-science-education-program)

UC Berkeley

Spring 2020

- Served as research lead for the undergraduate students and project partners involved in 40+ [data science discovery projects](https://data.berkeley.edu/research/discovery) 
- Developed [workshops](https://slides.com/jaeyeonkim) on project management, computational reproducibility, bias in machine learning, and data visualization
- Published [an article](https://ocean.sagepub.com/blog/skills/5-principles-to-get-undergraduates-involved-in-real-world-data-science-projects) on project management in SAGE Ocean 

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### An Introduction to Computational Tools and Techniques for Social Science Research (graduate) [[GitHub](https://github.com/jaeyk/PS239T)]

Lead Instructor 

UC Berkeley

Spring 2019

### Introduction to Empirical Analysis and Quantitative Methods (undergraduate)

Teaching Assistant

UC Berkeley

Fall 2016 

- Received [the outstanding graduate student instructor award](https://gsi.berkeley.edu/programs-services/award-programs/ogsi/ogsi-2017/), which is given to less than 10% of Berkeley TAs

::: aside 

- <i class="fas fa-star"></i> **Fellowships**: Visiting Democracy Fellowship, Ash Center for Democratic Governance and Innovation, Kennedy School, Harvard University (2020 - 2021, declined), D-Lab Data Science Fellowship, UC Berkeley (2020), Data Science Education Program Fellowship, UC Berkeley (2020), American Democracy Project Fellowship, UC Berkeley (2019), California Poverty and Socioeconomic Inequality Fellows Program, the Blum Initiative for Global and Regional Poverty Studies (2017), Berkeley Empirical Legal Studies Graduate Fellowship, Center for the Study of Law and Society, UC Berkeley (2017)

:::

Software {data-icon=laptop}
--------------------------------------------------------------

[**tidytweetjson**](https://github.com/jaeyk/tidytweetjson): R package for turning Tweet JSON files into a cleaned and wrangled dataset. The package takes 4.76 hours to turn 5 million tweets into a dataframe. 

[**tidyethnicnews**](https://github.com/jaeyk/tidyethnicnews): R package for turning search results from one of the largest databases on ethnic newspapers and magazines published in the United States into a cleaned and wrangled dataset. The package takes 28 seconds to turn 5,685 articles into a dataframe. 

[**makereproducible**](https://github.com/jaeyk/makereproducible): R package for making a project computationally reproducible before sharing it

Research Experience {data-icon=flask}
------------------------------------------------------------------------------
--

### [Large-scale Twitter Analysis on COVID-19 and Anti-Asian Climate](https://github.com/jaeyk/jaeyk.github.io/blob/master/_pages/project8.md) [[GitHub](https://github.com/jaeyk/covid19antiasian/)]

PhD Candidate 

UC Berkeley 

Summer 2020 - Present 

- Developed an [R package](https://github.com/jaeyk/tidytweetjson) that automates parsing a large Tweet JSON file (>5GB) into a cleaned and wrangled dataset
- Applied dynamic topic modeling to 1.4 million tweets and traced the rise of anti-Asian sentiment in the post-pandemic US
- Scheduled to present at the 2020 American Political Science Association annual meeting

### [Intersectional Bias in Hate Speech and Abusive Language Detection](https://jaeyk.github.io/_pages/project7/) Datasets [[GitHub](https://github.com/jaeyk/intersectional-bias-in-ml)] [[Preprint](https://arxiv.org/abs/2005.05921)] [[Slides](https://slides.com/jaeyeonkim/intersectional-bias-in-hate-speech-and-abusive-language-datasets/fullscreen)]

PhD Candidate 

UC Berkeley 

Spring 2020 - Present 

- Classified gender, racial, and party identities of the 100k tweets
- Demonstrated African American tweets were up to 3.7 times more likely to be labeled as abusive, and African American male tweets were up to 77% more likely to be labeled as hateful compared to the others
- Published the paper version in [*Proceedings of the Fourteenth International Conference on Web and Social Media (ICWSM), Data Challenge Workshop*](https://sites.google.com/view/icwsm2020datachallenge/home)

::: aside 

- <i class="fas fa-trophy"></i> **Awards**: Don T. Nakanishi Award for Distinguished Scholarship and Service in Asian Pacific American Politics, Western Political Science Association (2020), Outstanding Graduate Student Instructor Award, UC Berkeley (2016)

:::

### [Natural Language Processing and Machine Learning](https://jaeyk.github.io/_pages/project4/) [[GitHub](https://github.com/jaeyk/content-analysis-for-evaluating-ML-performances)] [[Preprint](https://osf.io/preprints/socarxiv/pg3aq/)] [[Slides](https://slides.com/jaeyeonkim/deck/fullscreen)]

PhD Candidate 

UC Berkeley 

2018 - Spring 2019

- Developed an [R package](https://github.com/jaeyk/tidyethnicnews) that automates parsing unstructured HTML files into a cleaned and wrangled dataset
- Demonstrated unreliable training data generates weak predictions and extreme interpretations using 80k+ historical newspaper articles
- Received [the Best Paper Award in Asian Pacific American Politics](https://www.wpsanet.org/award/) from the Western Political Science Association (2020)

### [Causal Inference and Machine Learning](https://jaeyk.github.io/_pages/project3/) [[GitHub](https://github.com/jaeyk/ITS-Text-Classification)]

PhD Candidate 

UC Berkeley 

Fall 2019 - Present

- Demonstrated how machine learning assists causal inference by combining text classification and interrupted time series design
- Presented at [the 2019 Data Science Showcase](https://bids.berkeley.edu/events/fall-2019-data-science-showcase) at UC Berkeley

### [Statistical Modeling of Time Series Data](https://jaeyk.github.io/_pages/project6/) [[GitHub](https://github.com/jaeyk/regression-analysis-with-time-series-data)] [[Preprint](https://osf.io/preprints/socarxiv/n83xs/?fbclid=IwAR0hjNshUloYDUxmgfK6DQ8arygUs_ePBWcTKUt0UDegyTcT9KTLefLYwGY)]

PhD Candidate 

UC Berkeley

2016 - 2018 

- Examined how social policy influenced community organizing among Asian Americans and Latinx by creating an original [organizational dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FLUPBJ) and modeling time-series data
- Authored a preprint, which was invited to Revise and Resubmit at [*Political Research Quarterly*](https://journals.sagepub.com/home/prq)

### [Survey and Experimental Research](https://jaeyk.github.io/_pages/project5/) [[GitHub](https://github.com/jaeyk/validating-two-linked-fates)]

Graduate Student 

UC Berkeley

2019 - Present

- Designed a within-subject experiment and embedded it in a California-wide survey to investigate how different racial groups interpret questions on racial solidarity differently 

### [Survey Research](https://jaeyk.github.io/_pages/project2/) [[GitHub](https://github.com/jaeyk/measuring-lived-racial-experience)]

Graduate Student Researcher

UC Berkeley

Summer 2018

- Cleaned and wrangled the largest panel survey data on Asian Americans, conducted factor and regression analyses, and visualized model outputs

Professional service {data-icon=commenting}
--------------------------------------------------------------------------------

Reviewer: Journal of Open Source Software

Organizing experience {data-icon=group}
--------------------------------------------------------------------------------

### [Summer Institute in Computational Social Science in the San Francisco Bay Area](https://compsocialscience.github.io/summer-institute/2020/bay_area/)

Co-organizer 

August 2019 - July 2020

- Raised 50k+, reviewed 100+ applicants and selected 20 participants 
- Developed close partnerships with nonprofits (e.g., Code for America, DonorsChoose, HopeLab)
- Designed the curriculum, guided the project development and developed the evaluation criteria
